import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import imagen from '../public/gy_logo.png';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">

      <body className={`p-0 m-0 flex flex-col dark:bg-zinc-950 bg-zinc-200 bg-cover w-screen h-screen`}>
        <header className="w-full h-20 dark:bg-zinc-900 bg-zinc-50 flex items-center justify-evenly text-center ">
          <Link className="text-zinc-950 dark:text-zinc-200 font-bold tracking-widest text-l basis-1/4" href={"/pages/characters"}>CHARACTERS</Link>
          {/* <h2 className={`${monserrat.className} text-zinc-950 dark:text-zinc-200 font-bold tracking-widest text-lg basis-2/4`}>GYCODING</h2> */}
          <Image className="hover:cursor-pointer" src={imagen} alt="Logo" width={70} height={50} />
          <Link className="text-zinc-950 dark:text-zinc-200 font-bold tracking-widest text-l basis-1/4" href={"/pages/worlds"}>WORLDS</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
